import type { Motorcycle, SourceSummary } from "@tm-ai/shared";

// Private development fixtures are synthetic and never point at a real case PDF.
const judicialSourceHome = "https://www.judicial.gov.tw/tw/lp-85-1.html";
const judicialUrls = {
  tcd38541: judicialSourceHome,
  ctd3888: judicialSourceHome,
  tnd8735: judicialSourceHome,
  tcd6257: judicialSourceHome,
  tpd201863: judicialSourceHome,
  ctd18413: judicialSourceHome,
  ksd2894: judicialSourceHome,
};

const history = [
  { observedAt: "2026-08-09T00:00:00Z", round: 1, reservePrice: 2000, currentPrice: 4300, soldPrice: null, status: "SCHEDULED" as const },
];

export const fixtureMotorcycles: Motorcycle[] = [
  {
    id: "53000000-0000-0000-0000-000000000001", sourceRecordId: "40000000-0000-0000-0000-000000000001", sourceAuid: "SYNTH-SHWOO-01",
    source: "shwoo", sourceName: "臺北惜物網", sourceFamily: "SHWOO", favoriteSupported: true,
    officialUrl: "https://shwoo.gov.taipei/shwoo/browse/browse00/", officialTitle: "【合成測試案件 A】機器腳踏車 1 台",
    name: "SYM HM12VB", brand: "SYM", model: "HM12VB", manufactureYear: 2011, manufactureMonth: 5, displacementCc: 125, vehicleClass: "ORDINARY_HEAVY", plateNumber: "TEST-SHWOO-01", color: "黃色",
    organization: "合成公營事業機關", location: "臺南市（測試地點）", county: "臺南市", disposalOrigin: "PUBLIC_ASSET_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-12T04:00:00Z", reservePrice: 2000, currentPrice: 4300, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: ["得標後之過戶與相關費用由得標人負擔"],
    bidEligibility: "NATURAL_PERSON_ALLOWED", registrationStatus: "RE_REGISTRATION_REQUIRED", hasKey: "UNKNOWN", canStart: "NO", canTest: "YES",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "目前車子發不動；僅提供靜態功能測試，無法道路測試。",
    riskBadges: ["目前無法發動", "需重新領牌", "現況點交"],
    imageUrl: "/api/fixture-media/939528-1", imageUrls: ["/api/fixture-media/939528-1", "/api/fixture-media/939528-2"],
    completeness: 84, completenessGroups: { identity: 100, auction: 100, condition: 80, registration: 100, fees: 67, media: 100 }, favorite: false,
    evidence: [
      { id: "e1", fieldName: "registration_status", sourceText: "合成測試：牌照已繳銷，領牌條件待確認。", officialUrl: "https://shwoo.gov.taipei/shwoo/browse/browse00/", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "e2", fieldName: "can_start", sourceText: "合成測試：目前無法發動，原因未確認。", officialUrl: "https://shwoo.gov.taipei/shwoo/browse/browse00/", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "e3", fieldName: "tax_arrears", sourceText: "合成測試：費用狀態以正式公告為準。", officialUrl: "https://shwoo.gov.taipei/shwoo/browse/browse00/", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history, duplicateCandidates: [],
  },
  {
    id: "fixture-939611", sourceRecordId: "fixture-sr-939611", sourceAuid: "SYNTH-SHWOO-02", officialUrl: "https://shwoo.gov.taipei/shwoo/browse/browse00/",
    source: "shwoo", sourceName: "臺北惜物網", sourceFamily: "SHWOO", favoriteSupported: true,
    officialTitle: "警用機車7臺(可領牌，需補稅)", name: "警用機車 7 臺", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, vehicleClass: "UNKNOWN",
    plateNumber: "TEST-BULK-01 等 7 面", color: null, organization: "合成地方警政機關", location: "苗栗縣（測試地點）", county: "苗栗縣", disposalOrigin: "PUBLIC_ASSET_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: null, auctionAt: "2026-08-12T04:00:00Z", reservePrice: 21000, currentPrice: 68500, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: ["牌照稅與燃料費依官方說明辦理"],
    bidEligibility: "NATURAL_PERSON_ALLOWED", registrationStatus: "RE_REGISTRATION_REQUIRED", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 7, bulkLot: true, conditionSummary: null, riskBadges: ["整批 7 臺", "需補稅", "車況未確認"], imageUrl: "/api/fixture-media/939611-1", imageUrls: ["/api/fixture-media/939611-1", "/api/fixture-media/939611-2", "/api/fixture-media/939611-3"],
    completeness: 45, completenessGroups: { identity: 20, auction: 100, condition: 0, registration: 60, fees: 20, media: 0 }, favorite: false, evidence: [], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-939179", sourceRecordId: "fixture-sr-939179", sourceAuid: "SYNTH-SHWOO-03", officialUrl: "https://shwoo.gov.taipei/shwoo/browse/browse00/",
    source: "shwoo", sourceName: "臺北惜物網", sourceFamily: "SHWOO", favoriteSupported: true,
    officialTitle: "普通重型電動機車（合成測試）", name: "普通重型電動機車", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, vehicleClass: "ELECTRIC_MOTORCYCLE",
    plateNumber: "TEST-ELECTRIC-01", color: null, organization: "合成臺北市機關", location: "臺北市（測試地點）", county: "臺北市", disposalOrigin: "PUBLIC_ASSET_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: null, auctionAt: "2026-08-10T04:00:00Z", reservePrice: 2000, currentPrice: 10600, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [],
    bidEligibility: "NATURAL_PERSON_ALLOWED", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: null, riskBadges: ["牌照狀態未確認", "電池狀態未確認"], imageUrl: "/api/fixture-media/939179-1", imageUrls: ["/api/fixture-media/939179-1", "/api/fixture-media/939179-2", "/api/fixture-media/939179-3"],
    completeness: 38, completenessGroups: { identity: 40, auction: 80, condition: 0, registration: 20, fees: 0, media: 0 }, favorite: false, evidence: [], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-pcc-70020198", sourceRecordId: "fixture-sr-pcc-70020198", sourceAuid: "70020198",
    source: "pcc", sourceName: "政府電子採購網財物變賣", sourceFamily: "PROCUREMENT", favoriteSupported: false,
    officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/indexAspam", officialTitle: "合成測試：報廢機車標售",
    name: "花蓮地院報廢機車標售批次", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, vehicleClass: "UNKNOWN", plateNumber: null, color: null,
    organization: "合成東部司法機關", location: "花蓮縣（測試地點）", county: "花蓮縣", disposalOrigin: "SCRAP_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-18T09:00:00Z", reservePrice: 800, currentPrice: null, soldPrice: null,
    deposit: 0, paymentDeadline: null, pickupDeadline: null, feeNotes: ["本案免收保證金"],
    bidEligibility: "LICENSED_RECYCLER_ONLY", registrationStatus: "SCRAP_ONLY", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: true, conditionSummary: "官方頁未提供可分離的車輛身分與車況，保留為整批標售。",
    riskBadges: ["限合格回收商", "不得領牌上路", "整批數量未確認"], imageUrl: null,
    completeness: 53, completenessGroups: { identity: 50, auction: 100, condition: 25, registration: 33, fees: 33, media: 0 }, favorite: false,
    evidence: [
      { id: "pcc-e1", fieldName: "eligibility", sourceText: "合成測試：本標售限具回收資格之業者。", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/indexAspam", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "pcc-e2", fieldName: "reserve_price", sourceText: "合成測試底價 800 元", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/indexAspam", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "pcc-e3", fieldName: "registration_status", sourceText: "合成測試：報廢機車標售", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/indexAspam", trust: "OFFICIAL_INFERRED", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-pcc-70020257", sourceRecordId: "fixture-sr-pcc-70020257", sourceAuid: "70020257",
    source: "pcc", sourceName: "政府電子採購網財物變賣", sourceFamily: "PROCUREMENT", favoriteSupported: false,
    officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/indexAspam", officialTitle: "合成測試：逾期未領回汽機車公開標售",
    name: "逾期未領回機車 4 輛", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, vehicleClass: "UNKNOWN", plateNumber: null, color: null,
    organization: "合成中部警政機關", location: "彰化縣（測試地點）", county: "彰化縣", disposalOrigin: "IMPOUNDED_UNCLAIMED",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-13T09:00:00Z", reservePrice: 134000, currentPrice: null, soldPrice: null,
    deposit: 2500, paymentDeadline: null, pickupDeadline: null, feeNotes: ["保證金新臺幣2,500元"],
    bidEligibility: "LICENSED_RECYCLER_ONLY", registrationStatus: "REGISTRABILITY_UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 4, bulkLot: true, conditionSummary: "官方摘要為交通違規移置保管逾期未領回車輛；個別車身資料未在此頁分列。",
    riskBadges: ["限合格回收商", "牌照狀態未確認", "整批 4 臺"], imageUrl: null,
    completeness: 55, completenessGroups: { identity: 100, auction: 100, condition: 25, registration: 33, fees: 33, media: 0 }, favorite: false,
    evidence: [
      { id: "pcc-e4", fieldName: "disposal_origin", sourceText: "合成測試：逾期未領回機車 4 輛", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/indexAspam", trust: "OFFICIAL_INFERRED", confidence: 1 },
      { id: "pcc-e5", fieldName: "reserve_price", sourceText: "合成測試底價 134,000 元", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/indexAspam", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tcd-38541", sourceRecordId: "fixture-sr-judicial-tcd-38541", sourceAuid: "TCD-115-038541-1",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: true,
    officialUrl: judicialUrls.tcd38541, officialTitle: "普通重型機車（合成司法測試 A）",
    name: "KYMCO SJ25HE", brand: "KYMCO", model: "SJ25HE", manufactureYear: 2009, manufactureMonth: 12, displacementCc: 124, vehicleClass: "ORDINARY_HEAVY", plateNumber: "TEST-COURT-01", color: null,
    organization: "臺灣臺中地方法院", location: null, county: "臺中市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-19T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN",
    hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN", mileageKm: null, lotSize: 1, bulkLot: false,
    conditionSummary: "官方中央查詢列出車牌、廠牌型號、排氣量與出廠年月；完整拍賣條款以法院公告 PDF 為準。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "底價未揭露"], imageUrl: null,
    completeness: 50, completenessGroups: { identity: 100, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [
      { id: "jud-e1", fieldName: "official_case_number", sourceText: "合成司法測試案號 A", officialUrl: judicialUrls.tcd38541, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e2", fieldName: "ends_at", sourceText: "1150819", officialUrl: judicialUrls.tcd38541, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e3", fieldName: "identity", sourceText: "合成測試車 A；普通重型；124 c.c.；2009 年 12 月", officialUrl: judicialUrls.tcd38541, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-ctd-3888", sourceRecordId: "fixture-sr-judicial-ctd-3888", sourceAuid: "CTD-114-003888-1",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: true,
    officialUrl: judicialUrls.ctd3888, officialTitle: "普通重型機車（合成司法測試 B）",
    name: "SYM TB16W6", brand: "SYM", model: "TB16W6", manufactureYear: 2023, manufactureMonth: 11, displacementCc: 158, vehicleClass: "ORDINARY_HEAVY", plateNumber: "TEST-COURT-02", color: null,
    organization: "臺灣橋頭地方法院", location: null, county: "高雄市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-27T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN",
    hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN", mileageKm: null, lotSize: 1, bulkLot: false,
    conditionSummary: "官方中央查詢之司法強制執行動產標的；保管地點、押標金與點交條款須查看官方公告 PDF。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "點交條款待查"], imageUrl: null,
    completeness: 50, completenessGroups: { identity: 100, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [
      { id: "jud-e4", fieldName: "official_case_number", sourceText: "合成司法測試案號 B", officialUrl: judicialUrls.ctd3888, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e5", fieldName: "identity", sourceText: "合成測試車 B；普通重型；158 c.c.；2023 年 11 月", officialUrl: judicialUrls.ctd3888, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tnd-8735", sourceRecordId: "fixture-sr-judicial-tnd-8735", sourceAuid: "TND-115-008735-1",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: true,
    officialUrl: judicialUrls.tnd8735, officialTitle: "普通重型機車（合成司法測試 C）",
    name: "YAMAHA 普通重型機車", brand: "YAMAHA", model: null, manufactureYear: null, manufactureMonth: null, displacementCc: 101, vehicleClass: "ORDINARY_HEAVY", plateNumber: "TEST-COURT-03", color: null,
    organization: "臺灣臺南地方法院", location: null, county: "臺南市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-09-24T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN",
    hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN", mileageKm: null, lotSize: 1, bulkLot: false,
    conditionSummary: "官方中央查詢列出的地院動產法拍；未揭露的車況、資格與價格均保留為未知。",
    riskBadges: ["投標資格未確認", "車況未確認", "底價未揭露"], imageUrl: null,
    completeness: 42, completenessGroups: { identity: 75, auction: 60, condition: 0, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [
      { id: "jud-e6", fieldName: "official_case_number", sourceText: "合成司法測試案號 C", officialUrl: judicialUrls.tnd8735, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e7", fieldName: "identity", sourceText: "合成測試車 C；普通重型；101 c.c.", officialUrl: judicialUrls.tnd8735, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tcd-6257", sourceRecordId: "fixture-sr-judicial-841439", sourceAuid: "841439",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: true,
    officialUrl: judicialUrls.tcd6257, officialTitle: "三陽普通重型機車",
    name: "SYM 普通重型機車", brand: "SYM", model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, vehicleClass: "ORDINARY_HEAVY", plateNumber: "TEST-COURT-04", color: null,
    organization: "臺灣臺中地方法院", location: null, county: "臺中市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 2, auctionAt: "2026-09-08T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "官方查詢僅明示車牌與第二拍；其餘車況及條款以法院公告 PDF 為準。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "底價未揭露"], imageUrl: null, completeness: 35,
    completenessGroups: { identity: 50, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e8", fieldName: "identity", sourceText: "合成測試車 D；普通重型；第 2 拍", officialUrl: judicialUrls.tcd6257, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tpd-201863", sourceRecordId: "fixture-sr-judicial-852659", sourceAuid: "852659",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: true,
    officialUrl: judicialUrls.tpd201863, officialTitle: "山葉機車",
    name: "YAMAHA XC100M", brand: "YAMAHA", model: "XC100M", manufactureYear: 2011, manufactureMonth: 12, displacementCc: 101, vehicleClass: "ORDINARY_HEAVY", plateNumber: "TEST-COURT-05", color: "白色",
    organization: "臺灣臺北地方法院", location: null, county: "臺北市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-21T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "依官方鑑定報告摘要，本件車輛保持完整；未因此推論可發動或可道路行駛。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "能否發動未確認"], imageUrl: null, completeness: 61,
    completenessGroups: { identity: 100, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e9", fieldName: "identity", sourceText: "合成測試車 E；2011 年 12 月；101 c.c.；白色", officialUrl: judicialUrls.tpd201863, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-ctd-18413", sourceRecordId: "fixture-sr-judicial-855400", sourceAuid: "855400",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: true,
    officialUrl: judicialUrls.ctd18413, officialTitle: "普通重型機車（合成司法測試 F）",
    name: "普通重型機車（司法測試）", brand: null, model: null, manufactureYear: 2023, manufactureMonth: 10, displacementCc: 124, vehicleClass: "ORDINARY_HEAVY", plateNumber: "TEST-COURT-06", color: null,
    organization: "臺灣橋頭地方法院", location: null, county: "高雄市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-27T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "官方結果明示 124cc、2023 年 10 月出廠、汽油；廠牌與車況未揭露。",
    riskBadges: ["廠牌未確認", "牌照狀態未確認", "底價未揭露"], imageUrl: null, completeness: 45,
    completenessGroups: { identity: 75, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e10", fieldName: "identity", sourceText: "合成測試車 F；普通重型；124 c.c.；2023 年 10 月", officialUrl: judicialUrls.ctd18413, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-ksd-2894", sourceRecordId: "fixture-sr-judicial-856121", sourceAuid: "856121",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: true,
    officialUrl: judicialUrls.ksd2894, officialTitle: "重型機車（合成司法測試 G）",
    name: "重型機車（級別未明）", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, vehicleClass: "HEAVY_UNSPECIFIED", plateNumber: "TEST-COURT-07", color: null,
    organization: "臺灣高雄地方法院", location: null, county: "高雄市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-09-10T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "中央結果僅明示重型機車與牌照號碼；未揭露欄位維持未知。",
    mediaNote: "這筆司法院中央結果的照片附件數為 0；官方 3 頁法院公告 PDF 也未內嵌照片，因此沒有可合法呈現的官方車照。",
    riskBadges: ["車況未確認", "投標資格未確認", "底價未揭露"], imageUrl: null, completeness: 30,
    completenessGroups: { identity: 50, auction: 60, condition: 0, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e11", fieldName: "identity", sourceText: "合成測試車 G；重型級別未明；第 1 拍", officialUrl: judicialUrls.ksd2894, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
];

export const fixtureSources: SourceSummary[] = [
  { id: "shwoo", name: "臺北惜物網", adapter: "shwoo", status: "PARTIAL", automationLevel: "公開唯讀", lastAttemptedAt: "2026-08-09T00:00:00Z", lastSuccessfulAt: null, discoveredCount: 9, changedCount: 3, parseSuccessRate: 100, warnings: ["等待本機資料庫首次完整同步後轉為 ACTIVE"] },
  { id: "judicial", name: "司法院 22 地院動產法拍", adapter: "judicial", status: "PARTIAL", automationLevel: "人工核對官方 PDF 清單／結構化匯入", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: ["中央查詢站不做自動 discovery；可匯入人工核對的官方 PDF 網址，等待替代 feed 後再全面自動化。"] },
  { id: "enforcement", name: "行政執行署動產拍賣", adapter: "moj_enforcement", status: "PARTIAL", automationLevel: "人工驗證後匯入／明細與照片自動保存", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: ["官方搜尋有 CAPTCHA；不自動破解，需人工匯出案件明細網址"] },
  { id: "pcc", name: "政府電子採購網財物變賣", adapter: "pcc", status: "DEGRADED", automationLevel: "授權複核中／不進無人排程", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: ["自動存取方式待書面確認，來源政策為 REVIEW_REQUIRED"] },
  { id: "moj-auction", name: "法務部查扣物集中拍賣", adapter: "moj_auction", status: "PARTIAL", automationLevel: "中央公開清單／公告、附件與照片保存", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: ["等待正式資料庫首次成功同步後才能標示為正式"] },
  { id: "police", name: "警政與交通機關直接公告", adapter: "police", status: "PLANNED", automationLevel: "採購網優先、機關頁補強", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: [] },
  { id: "customs", name: "海關拍賣", adapter: "customs", status: "PLANNED", automationLevel: "尚未實作", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: [] },
  { id: "mvdvan", name: "公路監理資料有償利用", adapter: "manual_mvdvan", status: "PLANNED", automationLevel: "每筆 2 元／人工授權補強", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: ["機車不提供里程欄位", "尚未設定付費帳號與逐筆扣款授權"] },
];
