import type { Motorcycle, SourceSummary } from "@tm-ai/shared";

const judicialPdf = (filename: string) => `https://aomp109.judicial.gov.tw/judbp/wkw/WHD1A02/DO_VIEWPDF.htm?filenm=${encodeURIComponent(filename)}`;
const judicialUrls = {
  tcd38541: judicialPdf("/tcd/11507/27190258947.021.pdf"),
  ctd3888: judicialPdf("/ctd/11507/15093846317.043.pdf"),
  tnd8735: judicialPdf("/tnd/11508/05153223684.017.pdf"),
  tcd6257: judicialPdf("/tcd/11507/13170852458.043.pdf"),
  tpd201863: judicialPdf("/tpd/11507/15101935218.041.pdf"),
  ctd18413: judicialPdf("/ctd/11508/03152010519.005.pdf"),
  ksd2894: judicialPdf("/ksd/11508/05144624865.020.pdf"),
};

const history = [
  { observedAt: "2026-08-09T00:00:00Z", round: 1, reservePrice: 2000, currentPrice: 4300, soldPrice: null, status: "SCHEDULED" as const },
];

export const fixtureMotorcycles: Motorcycle[] = [
  {
    id: "53000000-0000-0000-0000-000000000001", sourceRecordId: "40000000-0000-0000-0000-000000000001", sourceAuid: "939528",
    source: "shwoo", sourceName: "臺北惜物網", sourceFamily: "SHWOO", favoriteSupported: true,
    officialUrl: "https://shwoo.gov.taipei/shwoo/newproduct/newproduct00/product?AUID=939528", officialTitle: "【115Y431240018】機器腳踏車1台",
    name: "SYM HM12VB", brand: "SYM", model: "HM12VB", manufactureYear: 2011, manufactureMonth: 5, displacementCc: 125, plateNumber: "367-JSJ", color: "黃色",
    organization: "台灣電力股份有限公司台南區營業處", location: "臺南市永康區", county: "臺南市", disposalOrigin: "PUBLIC_ASSET_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-12T04:00:00Z", reservePrice: 2000, currentPrice: 4300, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: ["得標後之過戶與相關費用由得標人負擔"],
    bidEligibility: "NATURAL_PERSON_ALLOWED", registrationStatus: "RE_REGISTRATION_REQUIRED", hasKey: "UNKNOWN", canStart: "NO", canTest: "YES",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "目前車子發不動；僅提供靜態功能測試，無法道路測試。",
    riskBadges: ["目前無法發動", "需重新領牌", "現況點交"],
    imageUrl: "/api/fixture-media/939528-1", imageUrls: ["/api/fixture-media/939528-1", "/api/fixture-media/939528-2"],
    completeness: 84, completenessGroups: { identity: 100, auction: 100, condition: 80, registration: 100, fees: 67, media: 100 }, favorite: false,
    evidence: [
      { id: "e1", fieldName: "registration_status", sourceText: "已繳銷(可再領牌)", officialUrl: "https://shwoo.gov.taipei/shwoo/newproduct/newproduct00/product?AUID=939528", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "e2", fieldName: "can_start", sourceText: "目前車子發不動，不確定是否有那一部位機件故障，或電池沒電。", officialUrl: "https://shwoo.gov.taipei/shwoo/newproduct/newproduct00/product?AUID=939528", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "e3", fieldName: "tax_arrears", sourceText: "無欠稅及無道路交通違規事件。", officialUrl: "https://shwoo.gov.taipei/shwoo/newproduct/newproduct00/product?AUID=939528", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history, duplicateCandidates: [],
  },
  {
    id: "fixture-939611", sourceRecordId: "fixture-sr-939611", sourceAuid: "939611", officialUrl: "https://shwoo.gov.taipei/shwoo/newproduct/newproduct00/product?AUID=939611",
    source: "shwoo", sourceName: "臺北惜物網", sourceFamily: "SHWOO", favoriteSupported: true,
    officialTitle: "警用機車7臺(可領牌，需補稅)", name: "警用機車 7 臺", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null,
    plateNumber: "100-NKP 等 7 面", color: null, organization: "苗栗縣政府警察局", location: "苗栗縣後龍鎮", county: "苗栗縣", disposalOrigin: "PUBLIC_ASSET_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: null, auctionAt: "2026-08-12T04:00:00Z", reservePrice: 21000, currentPrice: 68500, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: ["牌照稅與燃料費依官方說明辦理"],
    bidEligibility: "NATURAL_PERSON_ALLOWED", registrationStatus: "RE_REGISTRATION_REQUIRED", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 7, bulkLot: true, conditionSummary: null, riskBadges: ["整批 7 臺", "需補稅", "車況未確認"], imageUrl: "/api/fixture-media/939611-1", imageUrls: ["/api/fixture-media/939611-1", "/api/fixture-media/939611-2", "/api/fixture-media/939611-3"],
    completeness: 45, completenessGroups: { identity: 20, auction: 100, condition: 0, registration: 60, fees: 20, media: 0 }, favorite: false, evidence: [], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-939179", sourceRecordId: "fixture-sr-939179", sourceAuid: "939179", officialUrl: "https://shwoo.gov.taipei/shwoo/newproduct/newproduct00/product?AUID=939179",
    source: "shwoo", sourceName: "臺北惜物網", sourceFamily: "SHWOO", favoriteSupported: true,
    officialTitle: "普通重型電動機車(EPD-0826)", name: "普通重型電動機車", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null,
    plateNumber: "EPD-0826", color: null, organization: "臺北市政府機關", location: "臺北市北投區", county: "臺北市", disposalOrigin: "PUBLIC_ASSET_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: null, auctionAt: "2026-08-10T04:00:00Z", reservePrice: 2000, currentPrice: 10600, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [],
    bidEligibility: "NATURAL_PERSON_ALLOWED", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: null, riskBadges: ["牌照狀態未確認", "電池狀態未確認"], imageUrl: "/api/fixture-media/939179-1", imageUrls: ["/api/fixture-media/939179-1", "/api/fixture-media/939179-2", "/api/fixture-media/939179-3"],
    completeness: 38, completenessGroups: { identity: 40, auction: 80, condition: 0, registration: 20, fees: 0, media: 0 }, favorite: false, evidence: [], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-pcc-70020198", sourceRecordId: "fixture-sr-pcc-70020198", sourceAuid: "70020198",
    source: "pcc", sourceName: "政府電子採購網財物變賣", sourceFamily: "PROCUREMENT", favoriteSupported: false,
    officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/readOneAspamDetailOld?pk=70020198", officialTitle: "標售本院115年奉准報廢機車",
    name: "花蓮地院報廢機車標售批次", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, plateNumber: null, color: null,
    organization: "臺灣花蓮地方法院", location: "花蓮縣花蓮市府前路15號", county: "花蓮縣", disposalOrigin: "SCRAP_DISPOSAL",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-18T09:00:00Z", reservePrice: 800, currentPrice: null, soldPrice: null,
    deposit: 0, paymentDeadline: null, pickupDeadline: null, feeNotes: ["本案免收保證金"],
    bidEligibility: "LICENSED_RECYCLER_ONLY", registrationStatus: "SCRAP_ONLY", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: true, conditionSummary: "官方頁未提供可分離的車輛身分與車況，保留為整批標售。",
    riskBadges: ["限合格回收商", "不得領牌上路", "整批數量未確認"], imageUrl: null,
    completeness: 53, completenessGroups: { identity: 50, auction: 100, condition: 25, registration: 33, fees: 33, media: 0 }, favorite: false,
    evidence: [
      { id: "pcc-e1", fieldName: "eligibility", sourceText: "投標人應為依法設立之公司或商業，並領有主管機關核准之廢機動車輛回收業資格。", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/readOneAspamDetailOld?pk=70020198", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "pcc-e2", fieldName: "reserve_price", sourceText: "底價金額 800", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/readOneAspamDetailOld?pk=70020198", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "pcc-e3", fieldName: "registration_status", sourceText: "標售本院115年奉准報廢機車", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/readOneAspamDetailOld?pk=70020198", trust: "OFFICIAL_INFERRED", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-pcc-70020257", sourceRecordId: "fixture-sr-pcc-70020257", sourceAuid: "70020257",
    source: "pcc", sourceName: "政府電子採購網財物變賣", sourceFamily: "PROCUREMENT", favoriteSupported: false,
    officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/readOneAspamDetailOld?pk=70020257", officialTitle: "交通違規移置保管逾期未領回汽機車公開標售案(汽車11輛、機車4輛)",
    name: "逾期未領回機車 4 輛", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, plateNumber: null, color: null,
    organization: "彰化縣警察局溪湖分局", location: "彰化縣溪湖鎮媽厝派出所", county: "彰化縣", disposalOrigin: "IMPOUNDED_UNCLAIMED",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-13T09:00:00Z", reservePrice: 134000, currentPrice: null, soldPrice: null,
    deposit: 2500, paymentDeadline: null, pickupDeadline: null, feeNotes: ["保證金新臺幣2,500元"],
    bidEligibility: "LICENSED_RECYCLER_ONLY", registrationStatus: "REGISTRABILITY_UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 4, bulkLot: true, conditionSummary: "官方摘要為交通違規移置保管逾期未領回車輛；個別車身資料未在此頁分列。",
    riskBadges: ["限合格回收商", "牌照狀態未確認", "整批 4 臺"], imageUrl: null,
    completeness: 55, completenessGroups: { identity: 100, auction: 100, condition: 25, registration: 33, fees: 33, media: 0 }, favorite: false,
    evidence: [
      { id: "pcc-e4", fieldName: "disposal_origin", sourceText: "交通違規移置保管逾期未領回汽機車公開標售案(汽車11輛、機車4輛)", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/readOneAspamDetailOld?pk=70020257", trust: "OFFICIAL_INFERRED", confidence: 1 },
      { id: "pcc-e5", fieldName: "reserve_price", sourceText: "底價金額 134,000", officialUrl: "https://web.pcc.gov.tw/opas/aspam/public/readOneAspamDetailOld?pk=70020257", trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tcd-38541", sourceRecordId: "fixture-sr-judicial-tcd-38541", sourceAuid: "TCD-115-038541-1",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: false,
    officialUrl: judicialUrls.tcd38541, officialTitle: "「721-GWL」普通重型機車",
    name: "KYMCO SJ25HE", brand: "KYMCO", model: "SJ25HE", manufactureYear: 2009, manufactureMonth: 12, displacementCc: 124, plateNumber: "721-GWL", color: null,
    organization: "臺灣臺中地方法院", location: null, county: "臺中市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-19T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN",
    hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN", mileageKm: null, lotSize: 1, bulkLot: false,
    conditionSummary: "官方中央查詢列出車牌、廠牌型號、排氣量與出廠年月；完整拍賣條款以法院公告 PDF 為準。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "底價未揭露"], imageUrl: null,
    completeness: 50, completenessGroups: { identity: 100, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [
      { id: "jud-e1", fieldName: "official_case_number", sourceText: "115司執字第038541號", officialUrl: judicialUrls.tcd38541, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e2", fieldName: "ends_at", sourceText: "1150819", officialUrl: judicialUrls.tcd38541, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e3", fieldName: "identity", sourceText: "「721-GWL」普通重型機車；廠牌：光陽，型號：SJ25HE，排氣量：124c.c.，出廠年月：2009年12月", officialUrl: judicialUrls.tcd38541, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-ctd-3888", sourceRecordId: "fixture-sr-judicial-ctd-3888", sourceAuid: "CTD-114-003888-1",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: false,
    officialUrl: judicialUrls.ctd3888, officialTitle: "「NWY-8337」普通重型機車",
    name: "SYM TB16W6", brand: "SYM", model: "TB16W6", manufactureYear: 2023, manufactureMonth: 11, displacementCc: 158, plateNumber: "NWY-8337", color: null,
    organization: "臺灣橋頭地方法院", location: null, county: "高雄市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-27T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN",
    hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN", mileageKm: null, lotSize: 1, bulkLot: false,
    conditionSummary: "官方中央查詢之司法強制執行動產標的；保管地點、押標金與點交條款須查看官方公告 PDF。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "點交條款待查"], imageUrl: null,
    completeness: 50, completenessGroups: { identity: 100, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [
      { id: "jud-e4", fieldName: "official_case_number", sourceText: "114司執助字第003888號", officialUrl: judicialUrls.ctd3888, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e5", fieldName: "identity", sourceText: "「NWY-8337」普通重型機車；廠牌：三陽，型號：TB16W6，排氣量：158c.c.，出廠年月：2023年11月", officialUrl: judicialUrls.ctd3888, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tnd-8735", sourceRecordId: "fixture-sr-judicial-tnd-8735", sourceAuid: "TND-115-008735-1",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: false,
    officialUrl: judicialUrls.tnd8735, officialTitle: "「510-JEP」普通重型機車",
    name: "YAMAHA 普通重型機車", brand: "YAMAHA", model: null, manufactureYear: null, manufactureMonth: null, displacementCc: 101, plateNumber: "510-JEP", color: null,
    organization: "臺灣臺南地方法院", location: null, county: "臺南市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-09-24T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN",
    hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN", mileageKm: null, lotSize: 1, bulkLot: false,
    conditionSummary: "官方中央查詢列出的地院動產法拍；未揭露的車況、資格與價格均保留為未知。",
    riskBadges: ["投標資格未確認", "車況未確認", "底價未揭露"], imageUrl: null,
    completeness: 42, completenessGroups: { identity: 75, auction: 60, condition: 0, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [
      { id: "jud-e6", fieldName: "official_case_number", sourceText: "115司執字第008735號", officialUrl: judicialUrls.tnd8735, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
      { id: "jud-e7", fieldName: "identity", sourceText: "「510-JEP」普通重型機車；廠牌：山葉；排氣量：101c.c.", officialUrl: judicialUrls.tnd8735, trust: "OFFICIAL_EXPLICIT", confidence: 1 },
    ], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tcd-6257", sourceRecordId: "fixture-sr-judicial-841439", sourceAuid: "841439",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: false,
    officialUrl: judicialUrls.tcd6257, officialTitle: "三陽普通重型機車",
    name: "SYM 普通重型機車", brand: "SYM", model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, plateNumber: "NQW-8226", color: null,
    organization: "臺灣臺中地方法院", location: null, county: "臺中市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 2, auctionAt: "2026-09-08T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "官方查詢僅明示車牌與第二拍；其餘車況及條款以法院公告 PDF 為準。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "底價未揭露"], imageUrl: null, completeness: 35,
    completenessGroups: { identity: 50, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e8", fieldName: "identity", sourceText: "三陽普通重型機車；車牌：NQW-8226；第2拍；1150908", officialUrl: judicialUrls.tcd6257, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-tpd-201863", sourceRecordId: "fixture-sr-judicial-852659", sourceAuid: "852659",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: false,
    officialUrl: judicialUrls.tpd201863, officialTitle: "山葉機車",
    name: "YAMAHA XC100M", brand: "YAMAHA", model: "XC100M", manufactureYear: 2011, manufactureMonth: 12, displacementCc: 101, plateNumber: "511-KND", color: "白色",
    organization: "臺灣臺北地方法院", location: null, county: "臺北市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-21T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "依官方鑑定報告摘要，本件車輛保持完整；未因此推論可發動或可道路行駛。",
    riskBadges: ["投標資格未確認", "牌照狀態未確認", "能否發動未確認"], imageUrl: null, completeness: 61,
    completenessGroups: { identity: 100, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e9", fieldName: "identity", sourceText: "車牌號碼：511-KND；廠牌：山葉、出廠年月：2011年12月、型式：XC100M、排氣量：101cc、顏色：白色、引擎：E3E4E-602216", officialUrl: judicialUrls.tpd201863, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-ctd-18413", sourceRecordId: "fixture-sr-judicial-855400", sourceAuid: "855400",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: false,
    officialUrl: judicialUrls.ctd18413, officialTitle: "普通重型機車（牌照號碼：NVX-2001）",
    name: "普通重型機車 NVX-2001", brand: null, model: null, manufactureYear: 2023, manufactureMonth: 10, displacementCc: 124, plateNumber: "NVX-2001", color: null,
    organization: "臺灣橋頭地方法院", location: null, county: "高雄市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-08-27T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "官方結果明示 124cc、2023 年 10 月出廠、汽油；廠牌與車況未揭露。",
    riskBadges: ["廠牌未確認", "牌照狀態未確認", "底價未揭露"], imageUrl: null, completeness: 45,
    completenessGroups: { identity: 75, auction: 60, condition: 25, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e10", fieldName: "identity", sourceText: "普通重型機車（牌照號碼：NVX-2001）；排氣量：124cc；出廠年月：2023年10月；燃料：汽油", officialUrl: judicialUrls.ctd18413, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
  {
    id: "fixture-judicial-ksd-2894", sourceRecordId: "fixture-sr-judicial-856121", sourceAuid: "856121",
    source: "judicial", sourceName: "司法院 22 地院動產法拍", sourceFamily: "JUDICIAL", favoriteSupported: false,
    officialUrl: judicialUrls.ksd2894, officialTitle: "重型機車（NEA-8168號）",
    name: "重型機車 NEA-8168", brand: null, model: null, manufactureYear: null, manufactureMonth: null, displacementCc: null, plateNumber: "NEA-8168", color: null,
    organization: "臺灣高雄地方法院", location: null, county: "高雄市", disposalOrigin: "JUDICIAL_EXECUTION",
    auctionStatus: "SCHEDULED", auctionRound: 1, auctionAt: "2026-09-10T00:00:00+08:00", auctionDatePrecision: "DATE", reservePrice: null, currentPrice: null, soldPrice: null,
    deposit: null, paymentDeadline: null, pickupDeadline: null, feeNotes: [], bidEligibility: "UNKNOWN", registrationStatus: "UNKNOWN", hasKey: "UNKNOWN", canStart: "UNKNOWN", canTest: "UNKNOWN",
    mileageKm: null, lotSize: 1, bulkLot: false, conditionSummary: "中央結果僅明示重型機車與牌照號碼；未揭露欄位維持未知。",
    mediaNote: "這筆司法院中央結果的照片附件數為 0；官方 3 頁法院公告 PDF 也未內嵌照片，因此沒有可合法呈現的官方車照。",
    riskBadges: ["車況未確認", "投標資格未確認", "底價未揭露"], imageUrl: null, completeness: 30,
    completenessGroups: { identity: 50, auction: 60, condition: 0, registration: 33, fees: 0, media: 0 }, favorite: false,
    evidence: [{ id: "jud-e11", fieldName: "identity", sourceText: "重型機車(NEA-8168號)；115司執字第002894號；第1拍；1150910", officialUrl: judicialUrls.ksd2894, trust: "OFFICIAL_EXPLICIT", confidence: 1 }], history: [], duplicateCandidates: [],
  },
];

export const fixtureSources: SourceSummary[] = [
  { id: "shwoo", name: "臺北惜物網", adapter: "shwoo", status: "PARTIAL", automationLevel: "公開唯讀", lastAttemptedAt: "2026-08-09T00:00:00Z", lastSuccessfulAt: null, discoveredCount: 9, changedCount: 3, parseSuccessRate: 100, warnings: ["等待本機資料庫首次完整同步後轉為 ACTIVE"] },
  { id: "judicial", name: "司法院 22 地院動產法拍", adapter: "judicial", status: "PARTIAL", automationLevel: "中央公開查詢／官方公告 PDF", lastAttemptedAt: "2026-08-11T00:00:00+08:00", lastSuccessfulAt: null, discoveredCount: 7, changedCount: 0, parseSuccessRate: null, warnings: ["正式資料庫同步尚未執行；目前展示本次官方查詢的 7 筆經清理範例"] },
  { id: "enforcement", name: "行政執行署拍賣", adapter: "moj_enforcement", status: "PLANNED", automationLevel: "CAPTCHA 安全／人工備援", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: [] },
  { id: "pcc", name: "政府電子採購網財物變賣", adapter: "pcc", status: "PARTIAL", automationLevel: "全國公開查詢／明細擷取", lastAttemptedAt: "2026-08-09T07:54:00Z", lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: ["正式資料庫同步尚未執行；目前展示 2 筆經清理的真實官方範例"] },
  { id: "prosecutors", name: "地方檢察署公告", adapter: "moj_cms", status: "PLANNED", automationLevel: "尚未實作", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: [] },
  { id: "police", name: "警政與交通機關直接公告", adapter: "police", status: "PLANNED", automationLevel: "採購網優先、機關頁補強", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: [] },
  { id: "customs", name: "海關拍賣", adapter: "customs", status: "PLANNED", automationLevel: "尚未實作", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: [] },
  { id: "mvdvan", name: "公路監理資料有償利用", adapter: "manual_mvdvan", status: "PLANNED", automationLevel: "每筆 2 元／人工授權補強", lastAttemptedAt: null, lastSuccessfulAt: null, discoveredCount: 0, changedCount: 0, parseSuccessRate: null, warnings: ["機車不提供里程欄位", "尚未設定付費帳號與逐筆扣款授權"] },
];
